name: .NET Build

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3.1.0
    - name: Nuget Restore
      run: nuget.exe restore
    - name: Build
      run: dotnet.exe build --configuration Release
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - name: Create Release-Merged
      id: create_release-merged
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest-merged"
        title: Release ${{ github.sha }}
        files: ./bin/Release/SharpSCCM_merged.exe
        prerelease: false
    - name: Create Release Zip File
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'SharpSCCM.zip'
        path: ./bin/Release/
    - name: Upload Release Zip
      id: create_release-zip
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: Release ${{ github.sha }}
        files: SharpSCCM.zip
        prerelease: false
