name: .NET Build

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3.1.0
    - name: Nuget Restore
      run: nuget.exe restore
    - name: Build
      run: dotnet.exe build --configuration Release
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - name: Find files
      run: dir /b /s
    - name: Create Release
      id: create_release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: Release ${{ github.sha }}
        files: ./SharpSCCM/bin/Release/SharpSCCM.exe
        prerelease: false
